spring:
  application:
    name: rabbitMq
  rabbitmq:
    virtual-host: my_vhost
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        # 开启消费者进行重试
        #enabled: true
        #指定最小的消费者数量.
        concurrency: 2
        #最大重试次数
        #max-attempts: 5
        # 重试时间间隔
        #initial-interval: 3000
        #指定最大的消费者数量
        max-concurrency: 10
        #开启ack，manual、 auto(默认)、none
        acknowledge-mode: manual
    template:
      #支持消息的确认与返回
      mandatory: true
      # 发送确认
    publisher-returns: true
    # 发送回调
    publisher-confirms: true
server:
  port: 8080